### ISSUE TITLE
除了3000端口，还能用什么端口呢？

### ISSUE THREAD

**Issue by fuyun-yipian** [HenryQW/OpenCC.henry.wang#7]
小白一个，问一个简单的问题，3000端口已经被占用，能换成其它端口吗？那些端口是可以使用的，比如端口1080或者8888可以使用吗？
```
docker run -d -p 8888:8888 --restart=always wangqiru/opencc-api-server
```
但是为什么使用不了呢？
![image](https://user-images.githubusercontent.com/56331646/66729603-17427780-ee7f-11e9-8777-ec4244331d66.png)

**Comment by HenryQW** [comment]
建议谷歌 docker publishes port

**Comment by fuyun-yipian** [comment]
已成功，多谢大佬指导！
